package attribution

import (
	"strings"
	"testing"
)

func cfg(t *testing.T) *Config {
	t.Helper()
	c, err := Default()
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func TestScrubCommitMessage(t *testing.T) {
	msg := "feat(pagos): reintento con idempotencia\n\nAgrega backoff exponencial.\n\n" +
		"Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n" +
		"Claude-Session: https://claude.ai/code/session_123\n" +
		"Co-authored-by: Ana Pérez <ana@example.com>\n" +
		"# Please enter the commit message for your changes.\n"
	out, found := cfg(t).ScrubLines(msg, true)
	if len(found) != 2 {
		t.Fatalf("se esperaban 2 hallazgos, hay %d: %+v", len(found), found)
	}
	for _, bad := range []string{"noreply@anthropic.com", "Claude-Session"} {
		if strings.Contains(out, bad) {
			t.Fatalf("quedó %q en:\n%s", bad, out)
		}
	}
	for _, good := range []string{"feat(pagos): reintento con idempotencia", "Agrega backoff", "Ana Pérez", "# Please enter"} {
		if !strings.Contains(out, good) {
			t.Fatalf("se perdió %q en:\n%s", good, out)
		}
	}
}

func TestFooters(t *testing.T) {
	c := cfg(t)
	footers := []string{
		"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
		"_Generated with [Claude Code](https://claude.com/claude-code)_",
		"> Generated by GitHub Copilot",
		"- Created with Windsurf",
		"<sub>Generated with [Claude Code](https://claude.com/claude-code)</sub>",
		"<sup>Written by [Cursor Bugbot](https://cursor.com/bugbot) for commit abc123.</sup>",
		":robot: Generated with Claude Code",
		"✨ Built with Codex",
		"This PR was generated with [Claude Code](https://claude.com/claude-code)",
		"Developed with Claude Code",
		"Desarrollado con Claude Code",
		"Este PR fue generado con Copilot",
		"Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
		"Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		"Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>",
		"Co-authored-by: Amp <amp@ampcode.com>",
		"Amp-Thread-ID: https://ampcode.com/threads/T-123",
		"https://chatgpt.com/codex/tasks/task_e_123",
		"Link to Devin run: https://app.devin.ai/sessions/abc",
	}
	for _, f := range footers {
		out, found := c.ScrubLines("feat: x\n\n"+f+"\n", true)
		if len(found) != 1 || strings.TrimSpace(out) != "feat: x" {
			t.Errorf("no se quitó %q: %+v -> %q", f, found, out)
		}
	}
}

func TestPhrasesInFiles(t *testing.T) {
	c := cfg(t)
	cases := map[string]string{
		"feat(api): endpoint de envíos generado con Claude":                        "feat(api): endpoint de envíos",
		"docs: guía de despliegue (escrita con ayuda de ChatGPT)":                  "docs: guía de despliegue",
		"Refactor the parser (written with Claude Code).":                          "Refactor the parser.",
		"Migración de esquema generada con Claude Code; revisada en QA.":           "Migración de esquema; revisada en QA.",
		"Tests (written with [Claude Code](https://claude.com/claude-code)) pass.": "Tests pass.",
	}
	for in, want := range cases {
		got, found := c.Scrub(in, false)
		if strings.TrimSpace(got) != want || len(found) != 1 {
			t.Errorf("Scrub(%q) = %q (%d hallazgos), se esperaba %q", in, got, len(found), want)
		}
	}
}

func TestPhrasesNotRewrittenInCommits(t *testing.T) {
	c := cfg(t)
	msg := "feat(api): endpoint generado con Claude Code\n\nCuerpo.\n"
	out, found := c.ScrubLines(msg, true)
	if len(found) != 0 || out != msg {
		t.Fatalf("ScrubLines no debe reescribir frases: %+v %q", found, out)
	}
	if p := c.Phrases(msg, true); len(p) != 1 || p[0].Line != 1 {
		t.Fatalf("Phrases debe reportar la frase del asunto: %+v", p)
	}
	if p := c.Phrases("aider: fix bug\n", true); len(p) != 1 {
		t.Fatalf("el prefijo aider: es atribución: %+v", p)
	}
}

func TestNoFalsePositives(t *testing.T) {
	c := cfg(t)
	ok := []string{
		"Claude Code es el runtime de los agentes; Coyote controla contexto y gates.",
		"feat(api): paginación basada en cursor para pedidos",
		"docs: soporte para Cursor, Windsurf, Copilot y Gemini CLI",
		"comparamos Copilot y Claude Code",
		"Co-authored-by: Devin Smith <devin@example.com>",
		"Co-authored-by: Claude Dupont <claude@example.fr>",
		"Co-authored-by: Haider Ali <haider@example.com>",
		"Co-authored-by: Sam Lee <sam@openai.com>",
		"Co-authored-by: Ana Ruiz <ana@anthropic.com>",
		"Co-authored-by: Jules Verne <jules@example.com>",
		"fix: reporte creado por el equipo de pagos",
		"fix: reject images made with AI in avatar uploads",
		"feat(moderación): detectar imágenes generadas con IA",
		"docs: add painting made by Claude Monet",
		"feat: robot 🤖 dance for the landing page",
		"Made by Devin Smith and the payments team",
		"La IA propone y la persona aprueba.",
	}
	for _, s := range ok {
		if f := c.Check(s, false); len(f) != 0 {
			t.Errorf("falso positivo en %q: %+v", s, f)
		}
	}
}

func TestLooseForCommands(t *testing.T) {
	c := cfg(t)
	for _, cmd := range []string{
		`git commit -m "feat: x" -m "Co-Authored-By: Claude <noreply@anthropic.com>"`,
		`git commit -m "feat: x" -m "Generated with [Claude Code](https://claude.com/claude-code)"`,
		`gh pr create --title x --body "Tests pass (written with Claude Code)"`,
	} {
		if len(c.Check(cmd, true)) == 0 {
			t.Errorf("no se detectó atribución en %s", cmd)
		}
	}
	if len(c.Check(`git commit -m "feat(api): nuevo endpoint"`, true)) != 0 {
		t.Fatal("falso positivo en un commit limpio")
	}
}

func TestAIIdentity(t *testing.T) {
	c := cfg(t)
	bots := [][2]string{
		{"Claude", "noreply@anthropic.com"},
		{"Cursor Agent", "cursoragent@cursor.com"},
		{"Copilot", "175728472+Copilot@users.noreply.github.com"},
		{"devin-ai-integration[bot]", "158243242+devin-ai-integration[bot]@users.noreply.github.com"},
	}
	for _, b := range bots {
		if _, ok := c.AIIdentity(b[0], b[1]); !ok {
			t.Errorf("%s <%s> es una identidad de IA", b[0], b[1])
		}
	}
	for _, h := range [][2]string{{"Claude Dupont", "claude@example.fr"}, {"Ana Pérez", "ana@example.com"}, {"Haider Ali", "haider@example.com"}} {
		if f, ok := c.AIIdentity(h[0], h[1]); ok {
			t.Errorf("%s es una persona: %+v", h[0], f)
		}
	}
}

func TestEmptyAndAllowed(t *testing.T) {
	c := cfg(t)
	out, _ := c.ScrubLines("Co-Authored-By: Claude <noreply@anthropic.com>\n# comentario\n", true)
	if !EmptyMessage(out) {
		t.Fatalf("el mensaje debería quedar vacío: %q", out)
	}
	if !c.Allowed("internal/x/testdata/footer.md") || c.Allowed("docs/specs/attribution-v1.md") {
		t.Fatal("rutas permitidas mal evaluadas")
	}
}

func TestComentariosDeGitConAtribucion(t *testing.T) {
	msg := "fix: algo\n\n# 🤖 Generated with [Claude Code](https://claude.com/claude-code)\n# On branch main\n"
	out, found := cfg(t).ScrubLines(msg, true)
	if len(found) != 1 || strings.Contains(out, "Claude Code") {
		t.Fatalf("la línea comentada con atribución debe salir: %+v\n%s", found, out)
	}
	if !strings.Contains(out, "# On branch main") {
		t.Fatalf("los comentarios normales de git se conservan:\n%s", out)
	}
}
