package attribution

import (
	"strings"
	"testing"
)

func cfg(t *testing.T) *Config {
	t.Helper()
	c, err := Default()
	if err != nil {
		t.Fatal(err)
	}
	return c
}

func TestScrubCommitMessage(t *testing.T) {
	msg := "feat(pagos): reintento con idempotencia\n\nAgrega backoff exponencial.\n\n" +
		"Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n" +
		"Claude-Session: https://claude.ai/code/session_123\n" +
		"Co-authored-by: Ana Pérez <ana@example.com>\n" +
		"# Please enter the commit message for your changes.\n"
	out, found := cfg(t).ScrubLines(msg, true)
	if len(found) != 2 {
		t.Fatalf("se esperaban 2 hallazgos, hay %d: %+v", len(found), found)
	}
	for _, bad := range []string{"noreply@anthropic.com", "Claude-Session"} {
		if strings.Contains(out, bad) {
			t.Fatalf("quedó %q en:\n%s", bad, out)
		}
	}
	for _, good := range []string{"feat(pagos): reintento con idempotencia", "Agrega backoff", "Ana Pérez", "# Please enter"} {
		if !strings.Contains(out, good) {
			t.Fatalf("se perdió %q en:\n%s", good, out)
		}
	}
}

func TestFooters(t *testing.T) {
	c := cfg(t)
	footers := []string{
		"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
		"_Generated with [Claude Code](https://claude.com/claude-code)_",
		"> Generated by GitHub Copilot",
		"- Created with Windsurf",
		"<sub>Generated with [Claude Code](https://claude.com/claude-code)</sub>",
		"<sup>Written by [Cursor Bugbot](https://cursor.com/bugbot) for commit abc123.</sup>",
		":robot: Generated with Claude Code",
		"✨ Built with Codex",
		"This PR was generated with [Claude Code](https://claude.com/claude-code)",
		"Developed with Claude Code",
		"Desarrollado con Claude Code",
		"Este PR fue generado con Copilot",
		"Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
		"Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		"Co-authored-by: claude[bot] <209825114+claude[bot]@users.noreply.github.com>",
		"Co-authored-by: cursor[bot] <206951365+cursor[bot]@users.noreply.github.com>",
		"Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>",
		"Co-authored-by: Amp <amp@ampcode.com>",
		"Co-authored-by : Claude <noreply@anthropic.com>",
		"Amp-Thread-ID: https://ampcode.com/threads/T-123",
		"https://chatgpt.com/codex/tasks/task_e_123",
		"Link to Devin run: https://app.devin.ai/sessions/abc",
	}
	for _, f := range footers {
		out, found := c.ScrubLines("feat: x\n\n"+f+"\n", true)
		if len(found) != 1 || strings.TrimSpace(out) != "feat: x" {
			t.Errorf("no se quitó %q: %+v -> %q", f, found, out)
		}
	}
}

func TestPhrasesAreReportedNotRewritten(t *testing.T) {
	c := cfg(t)
	phrases := []string{
		"feat(api): endpoint de envíos generado con Claude",
		"docs: guía de despliegue (escrita con ayuda de ChatGPT)",
		"Refactor the parser (written with Claude Code).",
		"Migración de esquema generada con Claude Code; revisada en QA.",
		"Tests (written with [Claude Code](https://claude.com/claude-code)) pass.",
		"Docs generated with [Claude Code](https://claude.com) for the API.",
		"parser, written with Claude Code, and tests.",
		"Steps (partly written with Claude Code):",
		"| parser | generado con Claude Code |",
		"aider: fix parser",
	}
	for _, in := range phrases {
		if p := c.Phrases(in, false); len(p) != 1 {
			t.Errorf("Phrases(%q) debería reportar una frase: %+v", in, p)
		}
		if out, found := c.ScrubLines(in, false); len(found) != 0 || strings.TrimSpace(out) != in {
			t.Errorf("ScrubLines no debe reescribir %q: %q", in, out)
		}
	}
}

func TestNoFalsePositives(t *testing.T) {
	c := cfg(t)
	ok := []string{
		"Claude Code es el runtime de los agentes; Coyote controla contexto y gates.",
		"feat(api): paginación basada en cursor para pedidos",
		"docs: soporte para Cursor, Windsurf, Copilot y Gemini CLI",
		"comparamos Copilot y Claude Code",
		"Co-authored-by: Devin Smith <devin@example.com>",
		"Co-authored-by: Claude Dupont <claude@example.fr>",
		"Co-authored-by: Haider Ali <haider@example.com>",
		"Co-authored-by: Sam Lee <sam@openai.com>",
		"Co-authored-by: Ana Ruiz <ana@anthropic.com>",
		"Co-authored-by: Jules Verne <jules@example.com>",
		"Co-authored-by: Bo Chen <bo@ampcode.com>",
		"Co-authored-by: Kim Park <kim@windsurf.com>",
		"Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
		"fix: reporte creado por el equipo de pagos",
		"fix: reject images made with AI in avatar uploads",
		"feat(moderación): detectar imágenes generadas con IA",
		"docs: add painting made by Claude Monet",
		"Made by Claude Monet in 1872.",
		"Written by Claude Dupont and Ana Ruiz.",
		"Hecho por Claude Dupont",
		"Built with Copilot in mind, not by it.",
		"feat: robot 🤖 dance for the landing page",
		"🤖 Move the cursor to the left",
		"🤖 fish &amp; chips",
		"ramp-run: yes",
		"Made by Devin Smith and the payments team",
		"La IA propone y la persona aprueba.",
	}
	for _, s := range ok {
		if f := c.Check(s, false); len(f) != 0 {
			t.Errorf("falso positivo en %q: %+v", s, f)
		}
	}
	for _, s := range []string{`git commit -m "docs: add painting made by Claude Monet"`, "git commit -m 'ci: ramp-run: yes'"} {
		if f := c.Check(s, true); len(f) != 0 {
			t.Errorf("falso positivo en el comando %q: %+v", s, f)
		}
	}
}

func TestLooseForCommands(t *testing.T) {
	c := cfg(t)
	for _, cmd := range []string{
		`git commit -m "feat: x" -m "Co-Authored-By: Claude <noreply@anthropic.com>"`,
		`git commit -m "feat: x" -m "Co-authored-by: claude[bot] <209825114+claude[bot]@users.noreply.github.com>"`,
		`git commit -m "feat: x" -m "Generated with [Claude Code](https://claude.com/claude-code)"`,
		`gh pr create --title x --body "Tests pass (written with Claude Code)"`,
	} {
		if len(c.Check(cmd, true)) == 0 {
			t.Errorf("no se detectó atribución en %s", cmd)
		}
	}
	if len(c.Check(`git commit -m "feat(api): nuevo endpoint"`, true)) != 0 {
		t.Fatal("falso positivo en un commit limpio")
	}
}

func TestAIIdentity(t *testing.T) {
	c := cfg(t)
	bots := [][2]string{
		{"Claude", "noreply@anthropic.com"},
		{"Cursor Agent", "cursoragent@cursor.com"},
		{"Copilot", "175728472+Copilot@users.noreply.github.com"},
		{"claude[bot]", "209825114+claude[bot]@users.noreply.github.com"},
		{"cursor[bot]", "206951365+cursor[bot]@users.noreply.github.com"},
		{"devin-ai-integration[bot]", "158243242+devin-ai-integration[bot]@users.noreply.github.com"},
		{"Amp", "amp@ampcode.com"},
	}
	for _, b := range bots {
		if _, ok := c.AIIdentity(b[0], b[1]); !ok {
			t.Errorf("%s <%s> es una identidad de IA", b[0], b[1])
		}
	}
	humans := [][2]string{
		{"Claude Dupont", "claude@example.fr"}, {"Ana Pérez", "ana@example.com"}, {"Haider Ali", "haider@example.com"},
		{"Bo Chen", "bo@ampcode.com"}, {"Kim Park", "kim@windsurf.com"}, {"Sam Lee", "sam@openai.com"},
		{"dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com"},
	}
	for _, h := range humans {
		if f, ok := c.AIIdentity(h[0], h[1]); ok {
			t.Errorf("%s no es una herramienta de IA: %+v", h[0], f)
		}
	}
}

func TestScissors(t *testing.T) {
	c := cfg(t)
	msg := "docs: limpia la guía\n\n# Please enter the commit message.\n" +
		"# ------------------------ >8 ------------------------\n" +
		"# Do not modify or remove the line above.\n" +
		"diff --git a/g.md b/g.md\n-Esta guía fue escrita con Claude Code.\n+Esta guía.\n" +
		"-Co-Authored-By: Claude <noreply@anthropic.com>\n"
	if p := c.Phrases(msg, true); len(p) != 0 {
		t.Fatalf("el diff de git commit -v no se revisa: %+v", p)
	}
	out, found := c.ScrubLines(msg, true)
	if len(found) != 0 || !strings.Contains(out, "-Co-Authored-By") {
		t.Fatalf("lo que va después de las tijeras no se toca: %+v\n%s", found, out)
	}
	if EmptyMessage("# ------------------------ >8 ------------------------\nfeat: x\n") != true {
		t.Fatal("el texto después de las tijeras no cuenta como mensaje")
	}
}

func TestEmptyAndAllowed(t *testing.T) {
	c := cfg(t)
	out, _ := c.ScrubLines("Co-Authored-By: Claude <noreply@anthropic.com>\n# comentario\n", true)
	if !EmptyMessage(out) {
		t.Fatalf("el mensaje debería quedar vacío: %q", out)
	}
	if !c.Allowed("internal/x/testdata/footer.md") || c.Allowed("docs/specs/attribution-v1.md") {
		t.Fatal("rutas permitidas mal evaluadas")
	}
}

func TestComentariosDeGitConAtribucion(t *testing.T) {
	msg := "fix: algo\n\n# 🤖 Generated with [Claude Code](https://claude.com/claude-code)\n# On branch main\n"
	out, found := cfg(t).ScrubLines(msg, true)
	if len(found) != 1 || strings.Contains(out, "Claude Code") {
		t.Fatalf("la línea comentada con atribución debe salir: %+v\n%s", found, out)
	}
	if !strings.Contains(out, "# On branch main") {
		t.Fatalf("los comentarios normales de git se conservan:\n%s", out)
	}
}
